/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author User
 */
public class InventoryGUI extends javax.swing.JFrame {

    /**
     * Creates new form InventoryGUI
     */
    
    private Connection conn;
    
    public InventoryGUI() throws Exception {
        initComponents();
        this.setSize(1065, 830);

        
        lblQuantityValue.setText(String.valueOf(quantitySlider.getValue()));
        //helper method that auto refresh all thing needed from db
        loadDashboardTable();
        refreshDashboardLabels();
        populateRemoveComboBox();
        populateUpdateComboBox();
        refreshAddItemTable();
        
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlDashboard = new javax.swing.JPanel();
        lblDashbord = new javax.swing.JLabel();
        lblDescriptionDashboard = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnRefreshDashboard = new javax.swing.JButton();
        lblDisplayDashboard = new javax.swing.JLabel();
        btnSortByPriceButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDisplayDashboard = new javax.swing.JTable();
        pnlAddItem = new javax.swing.JPanel();
        lblNewItem = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        lblItemType = new javax.swing.JLabel();
        cbItemType = new javax.swing.JComboBox<>();
        lblQuantity = new javax.swing.JLabel();
        quantitySlider = new javax.swing.JSlider();
        lblQuantityValue = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblDescriptionAddItem = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlRemoveItem = new javax.swing.JPanel();
        lblItemInventory = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        cbChooseItemRemove = new javax.swing.JComboBox<>();
        lblChooseItemRemove = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisplayItemRemove = new javax.swing.JTable();
        lblDescriptionRemoveItem = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblDisplayItemRemove = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlUpdateItem = new javax.swing.JPanel();
        lblUpdateInventory = new javax.swing.JLabel();
        lblChooseItemUpdate = new javax.swing.JLabel();
        cbChooseItemUpdate = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUpdateInventory = new javax.swing.JTable();
        lblDescriptionUpdateItem = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlSearchItem = new javax.swing.JPanel();
        lblSearchItem = new javax.swing.JLabel();
        lblEnterItemName = new javax.swing.JLabel();
        txtItemNameSearch = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSearchResult = new javax.swing.JTable();
        lblResultSearch = new javax.swing.JLabel();
        btnSearchByName = new javax.swing.JButton();
        lblDescriptionSearchItem = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnSearchByID = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        pnlTotalAssets = new javax.swing.JPanel();
        lblAssets = new javax.swing.JLabel();
        lblTotalAssets = new javax.swing.JLabel();
        lblDiamondPicture = new javax.swing.JLabel();
        pnlLowStockAlert = new javax.swing.JPanel();
        lblLowStockAlert = new javax.swing.JLabel();
        lblLowStock = new javax.swing.JLabel();
        lblWarningPicture = new javax.swing.JLabel();
        pnlTotalItems = new javax.swing.JPanel();
        lblItem = new javax.swing.JLabel();
        lblTotalItems = new javax.swing.JLabel();
        lblBoxPicture = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setForeground(new java.awt.Color(204, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N

        pnlDashboard.setBackground(new java.awt.Color(153, 255, 255, 50));
        pnlDashboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255)));

        lblDashbord.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        lblDashbord.setForeground(new java.awt.Color(255, 255, 255));
        lblDashbord.setText("Dashboard");

        lblDescriptionDashboard.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        lblDescriptionDashboard.setForeground(new java.awt.Color(204, 255, 255));
        lblDescriptionDashboard.setText("Viewing all Item in the Office Supplies inventory System Database");

        btnRefreshDashboard.setFont(new java.awt.Font("Segoe UI Semilight", 2, 14)); // NOI18N
        btnRefreshDashboard.setText("Refresh");
        btnRefreshDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshDashboardActionPerformed(evt);
            }
        });

        lblDisplayDashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lblDisplayDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplayDashboard.setText("All Item:");

        btnSortByPriceButton.setFont(new java.awt.Font("Segoe UI Semilight", 2, 14)); // NOI18N
        btnSortByPriceButton.setText("Sort by Price");
        btnSortByPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByPriceButtonActionPerformed(evt);
            }
        });

        tblDisplayDashboard.setBackground(new java.awt.Color(0, 102, 204));
        tblDisplayDashboard.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tblDisplayDashboard.setForeground(new java.awt.Color(255, 255, 255));
        tblDisplayDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Item Name", "Catgeory", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayDashboard.setRowHeight(34);
        tblDisplayDashboard.setShowGrid(true);
        jScrollPane6.setViewportView(tblDisplayDashboard);
        if (tblDisplayDashboard.getColumnModel().getColumnCount() > 0) {
            tblDisplayDashboard.getColumnModel().getColumn(0).setMinWidth(10);
            tblDisplayDashboard.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDashboardLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescriptionDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplayDashboard)))
                            .addGroup(pnlDashboardLayout.createSequentialGroup()
                                .addGap(320, 320, 320)
                                .addComponent(btnSortByPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRefreshDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 287, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblDashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDisplayDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortByPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Dashboard", pnlDashboard);

        pnlAddItem.setBackground(new java.awt.Color(153, 255, 255, 50));
        pnlAddItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));

        lblNewItem.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        lblNewItem.setForeground(new java.awt.Color(255, 255, 255));
        lblNewItem.setText("New Item Entry ");

        lblItemName.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(229, 255, 255));
        lblItemName.setText("Item Name:");

        txtItemName.setBackground(new java.awt.Color(232, 255, 255));
        txtItemName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });

        lblItemType.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lblItemType.setForeground(new java.awt.Color(230, 255, 255));
        lblItemType.setText("Category:");

        cbItemType.setBackground(new java.awt.Color(204, 255, 255));
        cbItemType.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        cbItemType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stationery", "Paper", "Furniture", "Electronics", "Printing", "Organization" }));

        lblQuantity.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(232, 255, 255));
        lblQuantity.setText("Quantity:");

        quantitySlider.setBackground(new java.awt.Color(204, 255, 255));
        quantitySlider.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        quantitySlider.setForeground(new java.awt.Color(255, 255, 255));
        quantitySlider.setMajorTickSpacing(50);
        quantitySlider.setMaximum(200);
        quantitySlider.setPaintLabels(true);
        quantitySlider.setPaintTicks(true);
        quantitySlider.setToolTipText("");
        quantitySlider.setValue(100);
        quantitySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantitySliderStateChanged(evt);
            }
        });

        lblQuantityValue.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        lblQuantityValue.setForeground(new java.awt.Color(209, 240, 255));
        lblQuantityValue.setText("100");

        btnAdd.setBackground(new java.awt.Color(238, 255, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI Light", 3, 15)); // NOI18N
        btnAdd.setText("Add to Inventory");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblInventory.setBackground(new java.awt.Color(0, 102, 204));
        tblInventory.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tblInventory.setForeground(new java.awt.Color(204, 255, 255));
        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Item Name", "Category", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventory.setRowHeight(30);
        tblInventory.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tblInventory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblInventory.setShowGrid(true);
        jScrollPane1.setViewportView(tblInventory);
        if (tblInventory.getColumnModel().getColumnCount() > 0) {
            tblInventory.getColumnModel().getColumn(0).setMinWidth(10);
            tblInventory.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(226, 255, 255));
        jLabel5.setText("Price:");

        lblDescriptionAddItem.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        lblDescriptionAddItem.setForeground(new java.awt.Color(229, 255, 255));
        lblDescriptionAddItem.setText("Add new item into the system and database");

        javax.swing.GroupLayout pnlAddItemLayout = new javax.swing.GroupLayout(pnlAddItem);
        pnlAddItem.setLayout(pnlAddItemLayout);
        pnlAddItemLayout.setHorizontalGroup(
            pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddItemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(375, 375, 375))
            .addGroup(pnlAddItemLayout.createSequentialGroup()
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddItemLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAddItemLayout.createSequentialGroup()
                                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItemName)
                                    .addComponent(quantitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblItemType)
                                    .addComponent(cbItemType, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblDescriptionAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAddItemLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(lblQuantityValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(pnlAddItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlAddItemLayout.setVerticalGroup(
            pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddItemLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionAddItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName)
                    .addComponent(lblItemType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbItemType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddItemLayout.createSequentialGroup()
                        .addComponent(quantitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantityValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                    .addGroup(pnlAddItemLayout.createSequentialGroup()
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Add Item", pnlAddItem);

        pnlRemoveItem.setBackground(new java.awt.Color(153, 255, 255, 50));
        pnlRemoveItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255)));

        lblItemInventory.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        lblItemInventory.setForeground(new java.awt.Color(255, 255, 255));
        lblItemInventory.setText("Remove Item");

        btnRemove.setBackground(new java.awt.Color(234, 255, 255));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnRemove.setText("Remove Item");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        cbChooseItemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChooseItemRemoveActionPerformed(evt);
            }
        });

        lblChooseItemRemove.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lblChooseItemRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseItemRemove.setText("Choose Item:");

        tblDisplayItemRemove.setBackground(new java.awt.Color(0, 102, 204));
        tblDisplayItemRemove.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tblDisplayItemRemove.setForeground(new java.awt.Color(204, 255, 255));
        tblDisplayItemRemove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Item Name", "Category", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayItemRemove.setRowHeight(30);
        tblDisplayItemRemove.setShowGrid(true);
        jScrollPane2.setViewportView(tblDisplayItemRemove);
        if (tblDisplayItemRemove.getColumnModel().getColumnCount() > 0) {
            tblDisplayItemRemove.getColumnModel().getColumn(0).setMinWidth(10);
            tblDisplayItemRemove.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        lblDescriptionRemoveItem.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        lblDescriptionRemoveItem.setForeground(new java.awt.Color(204, 255, 255));
        lblDescriptionRemoveItem.setText("Choose and remove any item in the system");

        lblDisplayItemRemove.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lblDisplayItemRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplayItemRemove.setText("Display Item:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Please select the item in table below");

        javax.swing.GroupLayout pnlRemoveItemLayout = new javax.swing.GroupLayout(pnlRemoveItem);
        pnlRemoveItem.setLayout(pnlRemoveItemLayout);
        pnlRemoveItemLayout.setHorizontalGroup(
            pnlRemoveItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemoveItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRemoveItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
            .addGroup(pnlRemoveItemLayout.createSequentialGroup()
                .addGroup(pnlRemoveItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRemoveItemLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlRemoveItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbChooseItemRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChooseItemRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescriptionRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDisplayItemRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRemoveItemLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlRemoveItemLayout.setVerticalGroup(
            pnlRemoveItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemoveItemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblItemInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionRemoveItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChooseItemRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbChooseItemRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblDisplayItemRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove Item", pnlRemoveItem);

        pnlUpdateItem.setBackground(new java.awt.Color(153, 255, 255, 50));
        pnlUpdateItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255)));

        lblUpdateInventory.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        lblUpdateInventory.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateInventory.setText("Update Inventory Item");

        lblChooseItemUpdate.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lblChooseItemUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseItemUpdate.setText("Choose Item to Update:");

        cbChooseItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChooseItemUpdateActionPerformed(evt);
            }
        });

        tblUpdateInventory.setBackground(new java.awt.Color(0, 102, 204));
        tblUpdateInventory.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tblUpdateInventory.setForeground(new java.awt.Color(204, 255, 255));
        tblUpdateInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Item Name", "Category", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUpdateInventory.setRowHeight(30);
        tblUpdateInventory.setShowGrid(true);
        jScrollPane3.setViewportView(tblUpdateInventory);
        if (tblUpdateInventory.getColumnModel().getColumnCount() > 0) {
            tblUpdateInventory.getColumnModel().getColumn(0).setMinWidth(10);
            tblUpdateInventory.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        lblDescriptionUpdateItem.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        lblDescriptionUpdateItem.setForeground(new java.awt.Color(204, 255, 255));
        lblDescriptionUpdateItem.setText("Choose any item to update");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Display Item:");

        btnUpdate.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 2, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Update item Category,Quantity or Price int the table below");

        javax.swing.GroupLayout pnlUpdateItemLayout = new javax.swing.GroupLayout(pnlUpdateItem);
        pnlUpdateItem.setLayout(pnlUpdateItemLayout);
        pnlUpdateItemLayout.setHorizontalGroup(
            pnlUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateItemLayout.createSequentialGroup()
                .addGroup(pnlUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5))
                    .addGroup(pnlUpdateItemLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnlUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbChooseItemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChooseItemUpdate)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUpdateItemLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUpdateInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescriptionUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpdateItemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(367, 367, 367))
        );
        pnlUpdateItemLayout.setVerticalGroup(
            pnlUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateItemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUpdateInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblChooseItemUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbChooseItemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnUpdate)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Inventory", pnlUpdateItem);

        pnlSearchItem.setBackground(new java.awt.Color(153, 255, 255, 50));
        pnlSearchItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255)));

        lblSearchItem.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        lblSearchItem.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchItem.setText("Search Item");

        lblEnterItemName.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lblEnterItemName.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterItemName.setText("Enter Item Name:");

        tblSearchResult.setBackground(new java.awt.Color(0, 102, 204));
        tblSearchResult.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tblSearchResult.setForeground(new java.awt.Color(204, 255, 255));
        tblSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Item Name", "Category", "Quantity", "Price"
            }
        ));
        tblSearchResult.setRowHeight(30);
        tblSearchResult.setShowGrid(true);
        tblSearchResult.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblSearchResult);
        if (tblSearchResult.getColumnModel().getColumnCount() > 0) {
            tblSearchResult.getColumnModel().getColumn(0).setMinWidth(10);
            tblSearchResult.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        lblResultSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lblResultSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblResultSearch.setText("Result:");

        btnSearchByName.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        btnSearchByName.setText("Search by Name");
        btnSearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByNameActionPerformed(evt);
            }
        });

        lblDescriptionSearchItem.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        lblDescriptionSearchItem.setForeground(new java.awt.Color(204, 255, 255));
        lblDescriptionSearchItem.setText("Search any item in the system by enter item name or id");

        btnSearchByID.setFont(new java.awt.Font("Segoe UI Semilight", 2, 14)); // NOI18N
        btnSearchByID.setText("Search by ID");
        btnSearchByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchItemLayout = new javax.swing.GroupLayout(pnlSearchItem);
        pnlSearchItem.setLayout(pnlSearchItemLayout);
        pnlSearchItemLayout.setHorizontalGroup(
            pnlSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchItemLayout.createSequentialGroup()
                .addGroup(pnlSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator6))
                    .addGroup(pnlSearchItemLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnlSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescriptionSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResultSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlSearchItemLayout.createSequentialGroup()
                                .addComponent(lblEnterItemName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtItemNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnSearchByID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchItemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSearchByName)
                .addGap(366, 366, 366))
        );
        pnlSearchItemLayout.setVerticalGroup(
            pnlSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchItemLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblSearchItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionSearchItem)
                .addGap(12, 12, 12)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnSearchByName)
                .addGap(4, 4, 4)
                .addComponent(lblResultSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Item", pnlSearchItem);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 240, 1020, 530);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255)));

        lblHeader.setFont(new java.awt.Font("Corbel", 0, 30)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("Office Supplies Inventory System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(598, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 60);

        pnlTotalAssets.setBackground(new java.awt.Color(153, 255, 255, 50));
        pnlTotalAssets.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));

        lblAssets.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblAssets.setForeground(new java.awt.Color(255, 255, 255));
        lblAssets.setText("Total Assets:");

        lblTotalAssets.setFont(new java.awt.Font("Segoe UI Semilight", 3, 33)); // NOI18N
        lblTotalAssets.setForeground(new java.awt.Color(0, 204, 255));
        lblTotalAssets.setText("RM 8900");

        lblDiamondPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/_(2 x 2 cm).png"))); // NOI18N

        javax.swing.GroupLayout pnlTotalAssetsLayout = new javax.swing.GroupLayout(pnlTotalAssets);
        pnlTotalAssets.setLayout(pnlTotalAssetsLayout);
        pnlTotalAssetsLayout.setHorizontalGroup(
            pnlTotalAssetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalAssetsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTotalAssetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalAssets)
                    .addComponent(lblAssets, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblDiamondPicture)
                .addGap(14, 14, 14))
        );
        pnlTotalAssetsLayout.setVerticalGroup(
            pnlTotalAssetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalAssetsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblAssets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalAssets, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalAssetsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDiamondPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlTotalAssets);
        pnlTotalAssets.setBounds(20, 80, 310, 120);

        pnlLowStockAlert.setBackground(new java.awt.Color(153, 255, 255, 50));
        pnlLowStockAlert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));

        lblLowStockAlert.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblLowStockAlert.setForeground(new java.awt.Color(255, 255, 255));
        lblLowStockAlert.setText("Low Stock Alert:");

        lblLowStock.setFont(new java.awt.Font("Segoe UI Light", 3, 36)); // NOI18N
        lblLowStock.setForeground(new java.awt.Color(0, 204, 255));
        lblLowStock.setText("5");

        lblWarningPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/warning(2 x 2 cm).png"))); // NOI18N

        javax.swing.GroupLayout pnlLowStockAlertLayout = new javax.swing.GroupLayout(pnlLowStockAlert);
        pnlLowStockAlert.setLayout(pnlLowStockAlertLayout);
        pnlLowStockAlertLayout.setHorizontalGroup(
            pnlLowStockAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLowStockAlertLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlLowStockAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLowStockAlert)
                    .addComponent(lblLowStock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWarningPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 106, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        pnlLowStockAlertLayout.setVerticalGroup(
            pnlLowStockAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLowStockAlertLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblLowStockAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLowStock, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlLowStockAlertLayout.createSequentialGroup()
                .addComponent(lblWarningPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLowStockAlert);
        pnlLowStockAlert.setBounds(720, 80, 310, 120);

        pnlTotalItems.setBackground(new java.awt.Color(153, 255, 255, 50));
        pnlTotalItems.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));

        lblItem.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblItem.setForeground(new java.awt.Color(255, 255, 255));
        lblItem.setText("Total Items:");

        lblTotalItems.setFont(new java.awt.Font("Segoe UI Semilight", 3, 36)); // NOI18N
        lblTotalItems.setForeground(new java.awt.Color(0, 204, 255));
        lblTotalItems.setText("300");

        lblBoxPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/box (2 x 2 cm) (2).png"))); // NOI18N

        javax.swing.GroupLayout pnlTotalItemsLayout = new javax.swing.GroupLayout(pnlTotalItems);
        pnlTotalItems.setLayout(pnlTotalItemsLayout);
        pnlTotalItemsLayout.setHorizontalGroup(
            pnlTotalItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalItemsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlTotalItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItem)
                    .addComponent(lblTotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblBoxPicture)
                .addContainerGap())
        );
        pnlTotalItemsLayout.setVerticalGroup(
            pnlTotalItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalItemsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(lblBoxPicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pnlTotalItems);
        pnlTotalItems.setBounds(370, 80, 310, 120);

        jSeparator1.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 220, 1040, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/6867640.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1050, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantitySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantitySliderStateChanged
        // TODO add your handling code here:
        int quantity = quantitySlider.getValue();
        lblQuantityValue.setText(String.valueOf(quantity));

        int r = 255 - (int) (quantity * (255.0 / 200.0));
        int g = 255 - (int) (quantity * (75.0 / 200.0));
        int b = 255;
        lblQuantityValue.setForeground(new java.awt.Color(r, g, b));
    }//GEN-LAST:event_quantitySliderStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            // ambil user input dari GUI
            String name = txtItemName.getText().trim();
            String category = cbItemType.getSelectedItem().toString();
            int quantity = quantitySlider.getValue();
            double price = Double.parseDouble(txtPrice.getText().trim());

            // generate random id using Random() method from 0-99
            int id = new java.util.Random().nextInt(100);

            //Create SupplyItem object
            SupplyItem item = new SupplyItem(id, name, category, quantity, price);

            //connect with database and add the item from SupplyItem Object
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            java.util.List<SupplyItem> items = new java.util.ArrayList<>();
            items.add(item);
            manager.addSupplyItem(items);

            //Show result in the GUI table
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblInventory.getModel();
            model.addRow(new Object[]{
                item.getId(),
                item.getName(),
                item.getCategory(),
                item.getQuantity(),
                item.getPrice()
            });
            //upadte combobox to newest item
            populateRemoveComboBox();
            populateUpdateComboBox();
            
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Item added successfully!",
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            refreshDashboardLabels();
            conn.close();
        } catch (InventoryException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: " + ex.getMessage(),
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter a valid price.",
                    "Input Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error adding item: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnAddActionPerformed


    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:

        try {
            // choose row to delete item
            int selectedRow = tblDisplayItemRemove.getSelectedRow();
            if (selectedRow == -1) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Please select an item to remove.",
                        "Selection Error",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //get id from the row of table
            int id = (int) tblDisplayItemRemove.getValueAt(selectedRow, 0);
            //connect with database as usual and delete the item from id
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            manager.deleteSupplyItem(id);
            
            //update cb
            populateRemoveComboBox();
            populateUpdateComboBox();

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Item removed successfully!",
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            refreshDashboardLabels();
            populateRemoveComboBox();
            cbChooseItemRemove.setSelectedIndex(-1);
            ((javax.swing.table.DefaultTableModel) tblDisplayItemRemove.getModel()).setRowCount(0); // clear table
            
            conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error removing item: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            //avoid error when in editting mode on the table
            if (tblUpdateInventory.isEditing()) {
                tblUpdateInventory.getCellEditor().stopCellEditing();
            }
            
            //get selected row as newest update
            int selectedRow = tblUpdateInventory.getSelectedRow();
            if (selectedRow == -1) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Please click the row in the table to confirm your update before pressing the button.",
                        "Confirmation Required",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblUpdateInventory.getModel();

            // get all attributes in the table that already updated
            int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
            String name = model.getValueAt(selectedRow, 1).toString();
            String category = model.getValueAt(selectedRow, 2).toString();
            int quantity = Integer.parseInt(model.getValueAt(selectedRow, 3).toString());
            double price = Double.parseDouble(model.getValueAt(selectedRow, 4).toString());
            
            //create supplyItem Object for the updated value
            SupplyItem updatedItem = new SupplyItem(id, name, category, quantity, price);
            
            // connect db and add the item in array
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            List<SupplyItem> items = new java.util.ArrayList<>();
            items.add(updatedItem);
            //call method updateStock to update in db
            manager.updateStock(items);
            
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Item updated successfully!",
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Refresh everything as usual to keep newest data
            loadDashboardTable();
            refreshDashboardLabels();
            populateRemoveComboBox();
            populateUpdateComboBox();
            conn.close();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter valid numeric values for Quantity and Price.",
                    "Input Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error updating item: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByNameActionPerformed
        // TODO add your handling code here:
        try {
            //get text first
            String searchName = txtItemNameSearch.getText().trim();

            // Check if search field is empty
            if (searchName.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Please enter an item name to search.",
                        "Input Required",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return; 
            }
            
            //connect db and create object manager
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);

            // get all item in db and pus as list items
            List<SupplyItem> items = manager.getAllSupplies();

            // Use lambda Predicate to filter by name
            List<SupplyItem> results = manager.filterItems(items,
                    item -> item.getName().toLowerCase().contains(searchName.toLowerCase()));

            // Display results in table
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblSearchResult.getModel();
            model.setRowCount(0); 
            for (SupplyItem item : results) {
                model.addRow(new Object[]{
                    item.getId(),
                    item.getName(),
                    item.getCategory(),
                    item.getQuantity(),
                    item.getPrice()
                });
            }
            
            if (results.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No items found matching: " + searchName,
                        "Search Result",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

           conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error searching items: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnSearchByNameActionPerformed

    private void btnRefreshDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDashboardActionPerformed
        // TODO add your handling code here:
        try {
            //connect db and get all item back if there is new item added and
            //not update in GUI
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            List<SupplyItem> items = manager.getAllSupplies();
            
            //show result in table
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblDisplayDashboard.getModel();
            model.setRowCount(0); 
            for (SupplyItem item : items) {
                model.addRow(new Object[]{
                    item.getId(),
                    item.getName(),
                    item.getCategory(),
                    item.getQuantity(),
                    item.getPrice()
                });
            }
            loadDashboardTable();
            refreshDashboardLabels();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Dashboard refreshed successfully!",
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error refreshing dashboard: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRefreshDashboardActionPerformed

    private void btnSortByPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByPriceButtonActionPerformed
        // TODO add your handling code here:
        try {
            
            //connect db and get all item in db as items list
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            List<SupplyItem> items = manager.getAllSupplies();

            // Sort using lambda expression method
            manager.sortByPrice(items);
            //display result in table
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblDisplayDashboard.getModel();
            model.setRowCount(0); 
            for (SupplyItem item : items) {
                model.addRow(new Object[]{
                    item.getId(),
                    item.getName(),
                    item.getCategory(),
                    item.getQuantity(),
                    item.getPrice()
                });
            }

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Items sorted by price (descending).",
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error sorting items: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSortByPriceButtonActionPerformed

    private void cbChooseItemRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChooseItemRemoveActionPerformed
        // TODO add your handling code here:
        //make sure the cb is not null,if null it return null. avoid error
        Object selected = cbChooseItemRemove.getSelectedItem();
        if (selected == null) {
            return;
        }

        try {
            // get select item in cb
            String selectedName = selected.toString();
            //connect db and get all items as items list
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            List<SupplyItem> items = manager.getAllSupplies();
            
            
            for (SupplyItem item : items) {
                //check if the items are equals with selected cb
                if (item.getName().equals(selectedName)) {
                    //update in table with the value
                    javax.swing.table.DefaultTableModel model
                            = (javax.swing.table.DefaultTableModel) tblDisplayItemRemove.getModel();
                    model.setRowCount(0);
                    model.addRow(new Object[]{
                        item.getId(),
                        item.getName(),
                        item.getCategory(),
                        item.getQuantity(),
                        item.getPrice()
                    });
                    break;
                }
            }
            conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error displaying item: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_cbChooseItemRemoveActionPerformed

    private void cbChooseItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChooseItemUpdateActionPerformed
        // TODO add your handling code here:
        //make sure the cb is not null,if null it return null. avoid error
        Object selected = cbChooseItemUpdate.getSelectedItem();
        if (selected == null) {
            return;
        }

        try {
            //get item in cb
            String selectedName = selected.toString();
            //connect db and get all items as items list
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            List<SupplyItem> items = manager.getAllSupplies();

            for (SupplyItem item : items) {
                //check if the items are equals with selected cb
                if (item.getName().equals(selectedName)) {
                    //update in table with the value
                    javax.swing.table.DefaultTableModel model
                            = (javax.swing.table.DefaultTableModel) tblUpdateInventory.getModel();
                    model.setRowCount(0); // clear previous
                    model.addRow(new Object[]{
                        item.getId(),
                        item.getName(),
                        item.getCategory(), 
                        item.getQuantity(), 
                        item.getPrice()
                    });
                    break;
                }
            }
            conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error displaying item: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_cbChooseItemUpdateActionPerformed

    private void btnSearchByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByIDActionPerformed
        // TODO add your handling code here:
        try {
            // Prompt user for ID input using pop up jOptionPane
            String input = javax.swing.JOptionPane.showInputDialog(this,
                    "Enter Item ID to search:",
                    "Search by ID",
                    javax.swing.JOptionPane.QUESTION_MESSAGE);

            // Check if user cancelled or left blank
            if (input == null || input.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Please enter a valid Item ID.",
                        "Input Required",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //get id
            int id = Integer.parseInt(input.trim());
            //connect db
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            
            //call getSupplyItem that use id for the parameter
            SupplyItem item = manager.getSupplyItem(id);
            
            //display result
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblSearchResult.getModel();
            model.setRowCount(0); 

            if (item != null) {
                // Add the found item to table
                model.addRow(new Object[]{
                    item.getId(),
                    item.getName(),
                    item.getCategory(),
                    item.getQuantity(),
                    item.getPrice()
                });
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No item found with ID: " + id,
                        "Search Result",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

            conn.close();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Item ID must be a number.",
                    "Input Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error searching item: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSearchByIDActionPerformed
    
    //========================== Helper Method =================================
    // Method to refresh table in add item page
    private void refreshAddItemTable() throws InventoryException {
        
        try {
            //connect db
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);

            // Get all items form db
            List<SupplyItem> allItems = manager.getAllSupplies();

            // Clear existing table data
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblInventory.getModel();
            model.setRowCount(0); 

            // Add new data to table
            for (SupplyItem item : allItems) {
                model.addRow(new Object[]{
                    item.getId(),
                    item.getName(),
                    item.getCategory(),
                    item.getQuantity(),
                    String.format("%.2f", item.getPrice())
                });
            }
            conn.close();
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error refreshing table: " + e.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    // Method to clear input fields after adding
    private void clearAddItemFields() {
        txtItemName.setText("");
        txtPrice.setText("");
        cbItemType.setSelectedIndex(0); // Reset to first category
        quantitySlider.setValue(100); // Reset to default value
        lblQuantityValue.setText("100");
    }

    //method to refresh the total assets,total item and low stock label
    private void refreshDashboardLabels() {
        try {
            //connect db and get all item
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            List<SupplyItem> items = manager.getAllSupplies();

            // use calculateTotaValue() and set text label
            double totalAssets = manager.calculateTotalValue(items);
            lblTotalAssets.setText("RM " + String.format("%.2f", totalAssets));

            //set text on the label
            lblTotalItems.setText(String.valueOf(items.size()));

            // call getLowStockCount() method and set text label
            int lowStockCount = manager.getLowStockCount(items);
            lblLowStock.setText(String.valueOf(lowStockCount));
            
            conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error refreshing dashboard labels: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //update remove combo box to newest items
    private void populateRemoveComboBox() {
        try {
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            List<SupplyItem> items = manager.getAllSupplies();

            cbChooseItemRemove.removeAllItems();
            for (SupplyItem item : items) {
                cbChooseItemRemove.addItem(item.getName());
            }
            conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading items: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //update update combo box to newest items
    private void populateUpdateComboBox() {
        try {
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            List<SupplyItem> items = manager.getAllSupplies();

            cbChooseItemUpdate.removeAllItems();
            for (SupplyItem item : items) {
                cbChooseItemUpdate.addItem(item.getName());
            }
            conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading items: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //load dashobard table with newest item in db
    private void loadDashboardTable() {
        try {
            conn = DBConnection.getConnection();
            InventoryManager manager = new InventoryManager(conn);
            List<SupplyItem> items = manager.getAllSupplies();

            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblDisplayDashboard.getModel();
            model.setRowCount(0); 
            for (SupplyItem item : items) {
                model.addRow(new Object[]{
                    item.getId(),
                    item.getName(),
                    item.getCategory(),
                    item.getQuantity(),
                    item.getPrice()
                });
            }
            
            conn.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading dashboard: " + ex.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InventoryGUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRefreshDashboard;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearchByID;
    private javax.swing.JButton btnSearchByName;
    private javax.swing.JButton btnSortByPriceButton;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbChooseItemRemove;
    private javax.swing.JComboBox<String> cbChooseItemUpdate;
    private javax.swing.JComboBox<String> cbItemType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAssets;
    private javax.swing.JLabel lblBoxPicture;
    private javax.swing.JLabel lblChooseItemRemove;
    private javax.swing.JLabel lblChooseItemUpdate;
    private javax.swing.JLabel lblDashbord;
    private javax.swing.JLabel lblDescriptionAddItem;
    private javax.swing.JLabel lblDescriptionDashboard;
    private javax.swing.JLabel lblDescriptionRemoveItem;
    private javax.swing.JLabel lblDescriptionSearchItem;
    private javax.swing.JLabel lblDescriptionUpdateItem;
    private javax.swing.JLabel lblDiamondPicture;
    private javax.swing.JLabel lblDisplayDashboard;
    private javax.swing.JLabel lblDisplayItemRemove;
    private javax.swing.JLabel lblEnterItemName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblItemInventory;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemType;
    private javax.swing.JLabel lblLowStock;
    private javax.swing.JLabel lblLowStockAlert;
    private javax.swing.JLabel lblNewItem;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantityValue;
    private javax.swing.JLabel lblResultSearch;
    private javax.swing.JLabel lblSearchItem;
    private javax.swing.JLabel lblTotalAssets;
    private javax.swing.JLabel lblTotalItems;
    private javax.swing.JLabel lblUpdateInventory;
    private javax.swing.JLabel lblWarningPicture;
    private javax.swing.JPanel pnlAddItem;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlLowStockAlert;
    private javax.swing.JPanel pnlRemoveItem;
    private javax.swing.JPanel pnlSearchItem;
    private javax.swing.JPanel pnlTotalAssets;
    private javax.swing.JPanel pnlTotalItems;
    private javax.swing.JPanel pnlUpdateItem;
    private javax.swing.JSlider quantitySlider;
    private javax.swing.JTable tblDisplayDashboard;
    private javax.swing.JTable tblDisplayItemRemove;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTable tblSearchResult;
    private javax.swing.JTable tblUpdateInventory;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemNameSearch;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
