/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthtrackingsystem;

import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class HealthTrackingSystemGUI extends javax.swing.JFrame {

    /**
     * Creates new form HealthTrackingSystemGUI
     */
    private TrackingList trackingList;

    public HealthTrackingSystemGUI() {
        initComponents();
        
        this.setSize(884, 725);
        jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI());
        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        
        
        trackingList = new TrackingList();
    }

    private void clearUserFields() {
        txtUserId.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtWeight.setText("");
        txtHeight.setText("");
        buttonGroup1.clearSelection();
    }

    private void clearActivityFields() {
        txtRecordID.setText("");
        txtUserID.setText("");
        txtDate.setText("");
        txtDuration.setText("");
    }

    private void clearNutritionFields() {
        txtRecordID2.setText("");
        txtUserID2.setText("");
        txtDate2.setText("");
    }

    private void clearSleepFields() {
        txtRecordID3.setText("");
        txtUserID3.setText("");
        txtDate3.setText("");
        txtHoursSlept.setText("");
    }

    private double getEstimatedCalories(String mealType) {
        switch (mealType) {
            case "Breakfast":
                return 400;
            case "Lunch":
                return 600;
            case "Dinner":
                return 700;
            case "Snack":
                return 200;
            default:
                return 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblUserId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        btnAddUser = new javax.swing.JButton();
        btnViewAllUsers = new javax.swing.JButton();
        btnCalculateUserBMI = new javax.swing.JButton();
        lblGender = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        btnReset1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblRecordID = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblActivityType = new javax.swing.JLabel();
        txtRecordID = new javax.swing.JTextField();
        txtUserID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnAddActivity = new javax.swing.JButton();
        btnViewAllActivities = new javax.swing.JButton();
        btnCalcCaloriesBurned = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDailyActivities = new javax.swing.JTextArea();
        btnGenerateRecordIdDA = new javax.swing.JButton();
        cbActivityType = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblManageNutritionRecords = new javax.swing.JLabel();
        lblRecordID2 = new javax.swing.JLabel();
        lblUserID2 = new javax.swing.JLabel();
        lblDate2 = new javax.swing.JLabel();
        lblMealType = new javax.swing.JLabel();
        txtRecordID2 = new javax.swing.JTextField();
        txtUserID2 = new javax.swing.JTextField();
        txtDate2 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnAddNutritionRecord = new javax.swing.JButton();
        btnViewAllNutritionRecords = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaNutritionRecord = new javax.swing.JTextArea();
        btnReset3 = new javax.swing.JButton();
        cbMealType = new javax.swing.JComboBox<>();
        btnCalculateTotalDailyCalories = new javax.swing.JButton();
        btnGenerateRecordIdNutrition = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblManageSleepRecords = new javax.swing.JLabel();
        lblRecordID3 = new javax.swing.JLabel();
        lblUserID3 = new javax.swing.JLabel();
        lblDate3 = new javax.swing.JLabel();
        lblHoursSlept = new javax.swing.JLabel();
        txtRecordID3 = new javax.swing.JTextField();
        txtUserID3 = new javax.swing.JTextField();
        txtDate3 = new javax.swing.JTextField();
        txtHoursSlept = new javax.swing.JTextField();
        btnReset4 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btnViewAllSleepRecords = new javax.swing.JButton();
        btnEvaluateSleepForRecord = new javax.swing.JButton();
        btnAddSleepRecord = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaSleepRecord = new javax.swing.JTextArea();
        btnGenerateRecordIdSleep = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUserID4 = new javax.swing.JLabel();
        txtUserID4 = new javax.swing.JTextField();
        btnDisplayAllHealthRecords = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtaReports = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        lblHealthTrackingSystem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(null);

        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(100, 195));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255, 30));

        lblUserId.setForeground(new java.awt.Color(255, 255, 255));
        lblUserId.setText("User ID:");

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name:");

        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age:");

        lblWeight.setForeground(new java.awt.Color(255, 255, 255));
        lblWeight.setText("Weight (kg):");

        lblHeight.setForeground(new java.awt.Color(255, 255, 255));
        lblHeight.setText("Height (m):");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manage Users");

        txtUserId.setBackground(new java.awt.Color(51, 0, 51));
        txtUserId.setForeground(new java.awt.Color(255, 255, 255));
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });

        txtName.setBackground(new java.awt.Color(51, 0, 51));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAge.setBackground(new java.awt.Color(51, 0, 51));
        txtAge.setForeground(new java.awt.Color(255, 255, 255));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtWeight.setBackground(new java.awt.Color(51, 0, 51));
        txtWeight.setForeground(new java.awt.Color(255, 255, 255));
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        txtHeight.setBackground(new java.awt.Color(51, 0, 51));
        txtHeight.setForeground(new java.awt.Color(255, 255, 255));
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        btnAddUser.setBackground(new java.awt.Color(51, 0, 51));
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnViewAllUsers.setBackground(new java.awt.Color(51, 0, 51));
        btnViewAllUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllUsers.setText("View All Users");
        btnViewAllUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllUsersActionPerformed(evt);
            }
        });

        btnCalculateUserBMI.setBackground(new java.awt.Color(51, 0, 51));
        btnCalculateUserBMI.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculateUserBMI.setText("Calculate User BMI");
        btnCalculateUserBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateUserBMIActionPerformed(evt);
            }
        });

        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender:");

        rbMale.setBackground(new java.awt.Color(51, 0, 51));
        buttonGroup1.add(rbMale);
        rbMale.setForeground(new java.awt.Color(255, 255, 255));
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });

        rbFemale.setBackground(new java.awt.Color(51, 0, 51));
        buttonGroup1.add(rbFemale);
        rbFemale.setForeground(new java.awt.Color(255, 255, 255));
        rbFemale.setText("Female");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });

        btnReset1.setBackground(new java.awt.Color(51, 0, 51));
        btnReset1.setForeground(new java.awt.Color(255, 255, 255));
        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(51, 0, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewAllUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCalculateUserBMI, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWeight)
                            .addComponent(lblHeight))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtHeight))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset1)
                .addGap(385, 385, 385))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserId)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(rbMale)
                    .addComponent(rbFemale))
                .addGap(20, 20, 20)
                .addComponent(btnReset1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAllUsers)
                    .addComponent(btnCalculateUserBMI)
                    .addComponent(btnAddUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Users", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Daily Activities");

        lblRecordID.setForeground(new java.awt.Color(255, 255, 255));
        lblRecordID.setText("Record ID:");

        lblUserID.setForeground(new java.awt.Color(255, 255, 255));
        lblUserID.setText("User ID:");

        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date(DD/MM/YYYY):");

        lblActivityType.setForeground(new java.awt.Color(255, 255, 255));
        lblActivityType.setText("Activity Type:");

        txtRecordID.setBackground(new java.awt.Color(51, 0, 51));
        txtRecordID.setForeground(new java.awt.Color(255, 255, 255));
        txtRecordID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecordIDActionPerformed(evt);
            }
        });

        txtUserID.setBackground(new java.awt.Color(51, 0, 51));
        txtUserID.setForeground(new java.awt.Color(255, 255, 255));
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });

        txtDate.setBackground(new java.awt.Color(51, 0, 51));
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        lblDuration.setBackground(new java.awt.Color(255, 255, 255));
        lblDuration.setForeground(new java.awt.Color(255, 255, 255));
        lblDuration.setText("Duration(hours):");

        txtDuration.setBackground(new java.awt.Color(51, 0, 51));
        txtDuration.setForeground(new java.awt.Color(255, 255, 255));
        txtDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurationActionPerformed(evt);
            }
        });

        btnAddActivity.setBackground(new java.awt.Color(51, 0, 51));
        btnAddActivity.setForeground(new java.awt.Color(255, 255, 255));
        btnAddActivity.setText("Add Activity");
        btnAddActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActivityActionPerformed(evt);
            }
        });

        btnViewAllActivities.setBackground(new java.awt.Color(51, 0, 51));
        btnViewAllActivities.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllActivities.setText("View All Activities");
        btnViewAllActivities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActivitiesActionPerformed(evt);
            }
        });

        btnCalcCaloriesBurned.setBackground(new java.awt.Color(51, 0, 51));
        btnCalcCaloriesBurned.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcCaloriesBurned.setText("Calculate Calories Burned for User");
        btnCalcCaloriesBurned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcCaloriesBurnedActionPerformed(evt);
            }
        });

        btnReset2.setBackground(new java.awt.Color(51, 0, 51));
        btnReset2.setForeground(new java.awt.Color(255, 255, 255));
        btnReset2.setText("Reset");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });

        txtaDailyActivities.setBackground(new java.awt.Color(51, 0, 51));
        txtaDailyActivities.setColumns(20);
        txtaDailyActivities.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtaDailyActivities.setForeground(new java.awt.Color(255, 255, 255));
        txtaDailyActivities.setRows(5);
        jScrollPane2.setViewportView(txtaDailyActivities);

        btnGenerateRecordIdDA.setBackground(new java.awt.Color(51, 0, 51));
        btnGenerateRecordIdDA.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateRecordIdDA.setText("Generate Record ID");
        btnGenerateRecordIdDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateRecordIdDAActionPerformed(evt);
            }
        });

        cbActivityType.setBackground(new java.awt.Color(51, 0, 51));
        cbActivityType.setForeground(new java.awt.Color(255, 255, 255));
        cbActivityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rest", "Walk", "Run" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset2)
                .addGap(371, 371, 371))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAddActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewAllActivities, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnCalcCaloriesBurned)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblActivityType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRecordID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDate)
                                    .addComponent(txtUserID)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGenerateRecordIdDA)))
                                .addGap(38, 38, 38)
                                .addComponent(lblDuration)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecordID)
                    .addComponent(txtRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuration)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateRecordIdDA))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActivityType)
                    .addComponent(cbActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnReset2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddActivity)
                    .addComponent(btnViewAllActivities)
                    .addComponent(btnCalcCaloriesBurned))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Daily Activities", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255, 30));

        lblManageNutritionRecords.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblManageNutritionRecords.setForeground(new java.awt.Color(255, 255, 255));
        lblManageNutritionRecords.setText("Manage Nutrition Records");

        lblRecordID2.setForeground(new java.awt.Color(255, 255, 255));
        lblRecordID2.setText("Record ID:");

        lblUserID2.setForeground(new java.awt.Color(255, 255, 255));
        lblUserID2.setText("User ID:");

        lblDate2.setForeground(new java.awt.Color(255, 255, 255));
        lblDate2.setText("Date(DD/MM/YYYY):");

        lblMealType.setForeground(new java.awt.Color(255, 255, 255));
        lblMealType.setText("Meal Type:");

        txtRecordID2.setBackground(new java.awt.Color(51, 0, 51));
        txtRecordID2.setForeground(new java.awt.Color(255, 255, 255));
        txtRecordID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecordID2ActionPerformed(evt);
            }
        });

        txtUserID2.setBackground(new java.awt.Color(51, 0, 51));
        txtUserID2.setForeground(new java.awt.Color(255, 255, 255));
        txtUserID2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserID2ActionPerformed(evt);
            }
        });

        txtDate2.setBackground(new java.awt.Color(51, 0, 51));
        txtDate2.setForeground(new java.awt.Color(255, 255, 255));
        txtDate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate2ActionPerformed(evt);
            }
        });

        btnAddNutritionRecord.setBackground(new java.awt.Color(51, 0, 51));
        btnAddNutritionRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNutritionRecord.setText("Add Nutrition Record");
        btnAddNutritionRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNutritionRecordActionPerformed(evt);
            }
        });

        btnViewAllNutritionRecords.setBackground(new java.awt.Color(51, 0, 51));
        btnViewAllNutritionRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllNutritionRecords.setText("View All Nutrition Records");
        btnViewAllNutritionRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllNutritionRecordsActionPerformed(evt);
            }
        });

        txtaNutritionRecord.setBackground(new java.awt.Color(51, 0, 51));
        txtaNutritionRecord.setColumns(20);
        txtaNutritionRecord.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtaNutritionRecord.setForeground(new java.awt.Color(255, 255, 255));
        txtaNutritionRecord.setRows(5);
        jScrollPane3.setViewportView(txtaNutritionRecord);

        btnReset3.setBackground(new java.awt.Color(51, 0, 51));
        btnReset3.setForeground(new java.awt.Color(255, 255, 255));
        btnReset3.setText("Reset");
        btnReset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset3ActionPerformed(evt);
            }
        });

        cbMealType.setBackground(new java.awt.Color(51, 0, 51));
        cbMealType.setForeground(new java.awt.Color(255, 255, 255));
        cbMealType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast", "Lunch", "Dinner", "Snack" }));
        cbMealType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMealTypeActionPerformed(evt);
            }
        });

        btnCalculateTotalDailyCalories.setBackground(new java.awt.Color(51, 0, 51));
        btnCalculateTotalDailyCalories.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculateTotalDailyCalories.setText("Calculate Total Daily Calories");
        btnCalculateTotalDailyCalories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateTotalDailyCaloriesActionPerformed(evt);
            }
        });

        btnGenerateRecordIdNutrition.setBackground(new java.awt.Color(51, 0, 51));
        btnGenerateRecordIdNutrition.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateRecordIdNutrition.setText("Generate Record ID");
        btnGenerateRecordIdNutrition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateRecordIdNutritionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManageNutritionRecords)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblUserID2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDate2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMealType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblRecordID2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbMealType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(txtRecordID2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(152, 152, 152)))
                                    .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnAddNutritionRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnViewAllNutritionRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculateTotalDailyCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(btnReset3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserID2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerateRecordIdNutrition, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblManageNutritionRecords)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecordID2)
                    .addComponent(txtRecordID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateRecordIdNutrition))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID2)
                    .addComponent(txtUserID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate2)
                    .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMealType)
                    .addComponent(cbMealType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnReset3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNutritionRecord)
                    .addComponent(btnViewAllNutritionRecords)
                    .addComponent(btnCalculateTotalDailyCalories))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nutrition", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255, 30));

        lblManageSleepRecords.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblManageSleepRecords.setForeground(new java.awt.Color(255, 255, 255));
        lblManageSleepRecords.setText("Manage Sleep Records");

        lblRecordID3.setForeground(new java.awt.Color(255, 255, 255));
        lblRecordID3.setText("Record ID:");

        lblUserID3.setForeground(new java.awt.Color(255, 255, 255));
        lblUserID3.setText("User ID:");

        lblDate3.setForeground(new java.awt.Color(255, 255, 255));
        lblDate3.setText("Date (DD/MM/YYYY):");

        lblHoursSlept.setForeground(new java.awt.Color(255, 255, 255));
        lblHoursSlept.setText("Hours Slept:");

        txtRecordID3.setBackground(new java.awt.Color(51, 0, 51));
        txtRecordID3.setForeground(new java.awt.Color(255, 255, 255));
        txtRecordID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecordID3ActionPerformed(evt);
            }
        });

        txtUserID3.setBackground(new java.awt.Color(51, 0, 51));
        txtUserID3.setForeground(new java.awt.Color(255, 255, 255));
        txtUserID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserID3ActionPerformed(evt);
            }
        });

        txtDate3.setBackground(new java.awt.Color(51, 0, 51));
        txtDate3.setForeground(new java.awt.Color(255, 255, 255));
        txtDate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate3ActionPerformed(evt);
            }
        });

        txtHoursSlept.setBackground(new java.awt.Color(51, 0, 51));
        txtHoursSlept.setForeground(new java.awt.Color(255, 255, 255));
        txtHoursSlept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoursSleptActionPerformed(evt);
            }
        });

        btnReset4.setBackground(new java.awt.Color(51, 0, 51));
        btnReset4.setForeground(new java.awt.Color(255, 255, 255));
        btnReset4.setText("Reset");
        btnReset4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset4ActionPerformed(evt);
            }
        });

        btnViewAllSleepRecords.setBackground(new java.awt.Color(51, 0, 51));
        btnViewAllSleepRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllSleepRecords.setText("View All Sleep Records");
        btnViewAllSleepRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllSleepRecordsActionPerformed(evt);
            }
        });

        btnEvaluateSleepForRecord.setBackground(new java.awt.Color(51, 0, 51));
        btnEvaluateSleepForRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnEvaluateSleepForRecord.setText("Evaluate Sleep for Record");
        btnEvaluateSleepForRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluateSleepForRecordActionPerformed(evt);
            }
        });

        btnAddSleepRecord.setBackground(new java.awt.Color(51, 0, 51));
        btnAddSleepRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSleepRecord.setText("Add Sleep Record");
        btnAddSleepRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSleepRecordActionPerformed(evt);
            }
        });

        txtaSleepRecord.setBackground(new java.awt.Color(51, 0, 51));
        txtaSleepRecord.setColumns(20);
        txtaSleepRecord.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtaSleepRecord.setForeground(new java.awt.Color(255, 255, 255));
        txtaSleepRecord.setRows(5);
        jScrollPane4.setViewportView(txtaSleepRecord);

        btnGenerateRecordIdSleep.setBackground(new java.awt.Color(51, 0, 51));
        btnGenerateRecordIdSleep.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateRecordIdSleep.setText("Genarate Record ID");
        btnGenerateRecordIdSleep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateRecordIdSleepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblManageSleepRecords)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblRecordID3)
                                                .addComponent(lblUserID3))
                                            .addGap(78, 78, 78)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtUserID3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                    .addComponent(txtRecordID3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnGenerateRecordIdSleep))))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDate3)
                                                .addComponent(lblHoursSlept))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDate3)
                                                .addComponent(txtHoursSlept))))
                                    .addComponent(btnReset4)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnAddSleepRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewAllSleepRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEvaluateSleepForRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblManageSleepRecords)
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecordID3)
                    .addComponent(txtRecordID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateRecordIdSleep))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID3)
                    .addComponent(txtUserID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate3)
                    .addComponent(txtDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoursSlept)
                    .addComponent(txtHoursSlept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnReset4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAllSleepRecords)
                    .addComponent(btnEvaluateSleepForRecord)
                    .addComponent(btnAddSleepRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sleep", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255, 30));
        jPanel5.setForeground(java.awt.Color.red);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reports");

        lblUserID4.setForeground(new java.awt.Color(255, 255, 255));
        lblUserID4.setText("User ID:");

        txtUserID4.setBackground(new java.awt.Color(51, 0, 51));
        txtUserID4.setForeground(new java.awt.Color(255, 255, 255));
        txtUserID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserID4ActionPerformed(evt);
            }
        });

        btnDisplayAllHealthRecords.setBackground(new java.awt.Color(51, 0, 51));
        btnDisplayAllHealthRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplayAllHealthRecords.setText("Display All Health Records");
        btnDisplayAllHealthRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayAllHealthRecordsActionPerformed(evt);
            }
        });

        txtaReports.setBackground(new java.awt.Color(51, 0, 51));
        txtaReports.setColumns(20);
        txtaReports.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtaReports.setForeground(new java.awt.Color(255, 255, 255));
        txtaReports.setRows(5);
        jScrollPane5.setViewportView(txtaReports);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblUserID4)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserID4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnDisplayAllHealthRecords)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID4)
                    .addComponent(txtUserID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayAllHealthRecords))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Reports", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(6, 66, 850, 610);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-6, 60, 870, 10);

        lblHealthTrackingSystem.setFont(new java.awt.Font("Book Antiqua", 1, 30)); // NOI18N
        lblHealthTrackingSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblHealthTrackingSystem.setText("Health Tracking System");
        getContentPane().add(lblHealthTrackingSystem);
        lblHealthTrackingSystem.setBounds(10, 10, 360, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\bg3.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 870, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtRecordIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecordIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecordIDActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnAddActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActivityActionPerformed
        // TODO add your handling code here:
        int recordId = Integer.parseInt(txtRecordID.getText());
        int userId = Integer.parseInt(txtUserID.getText());
        String date = txtDate.getText();
        String activityType = cbActivityType.getSelectedItem().toString();
        double duration = Double.parseDouble(txtDuration.getText());

        if (date.trim().isEmpty() || activityType.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Date and Activity Type are required.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        User user = trackingList.findUser(userId);
        if (user == null) {
            JOptionPane.showMessageDialog(this, "User ID does not exist! Please add user first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (trackingList.isRecordIdExist(recordId)) {
            JOptionPane.showMessageDialog(this, "Record ID already exist!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DailyActivity newActivity = new DailyActivity(activityType, duration, user, userId, recordId, date);
        double caloriesBurned = newActivity.calculateCaloriesBurned();
        trackingList.addHealthRecord(newActivity);
        JOptionPane.showMessageDialog(this, "Daily Activity added successfully!");
        clearActivityFields();
    }//GEN-LAST:event_btnAddActivityActionPerformed

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        // TODO add your handling code here:
        clearActivityFields();
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnViewAllActivitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActivitiesActionPerformed
        // TODO add your handling code here:
        displayAllRecords();
    }//GEN-LAST:event_btnViewAllActivitiesActionPerformed

    private void txtRecordID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecordID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecordID2ActionPerformed

    private void btnAddNutritionRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNutritionRecordActionPerformed
        // TODO add your handling code here:
        int recordId = Integer.parseInt(txtRecordID2.getText());
        int userId = Integer.parseInt(txtUserID2.getText());
        String date = txtDate2.getText();
        String mealType = cbMealType.getSelectedItem().toString();

        if (date.trim().isEmpty() || mealType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Date and select Meal Type.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        User user = trackingList.findUser(userId);
        if (user == null) {
            JOptionPane.showMessageDialog(this, "User ID does not exist! Please add user first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (trackingList.isRecordIdExist(recordId)) {
            JOptionPane.showMessageDialog(this, "Record ID already exist!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double calories = getEstimatedCalories(mealType);

        NutritionRecord newNutritionRecord = new NutritionRecord(mealType, calories, user, userId, recordId, date);
        trackingList.addHealthRecord(newNutritionRecord);

        JOptionPane.showMessageDialog(this, "Nutrition Record added successfully!");

        clearNutritionFields();

    }//GEN-LAST:event_btnAddNutritionRecordActionPerformed

    private void btnReset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset3ActionPerformed
        // TODO add your handling code here:
        clearNutritionFields();
    }//GEN-LAST:event_btnReset3ActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        int userId = Integer.parseInt(txtUserId.getText());
        String name = txtName.getText();
        int age = Integer.parseInt(txtAge.getText());
        double weight = Double.parseDouble(txtWeight.getText());
        double height = Double.parseDouble(txtHeight.getText());
        String gender = "";
        if (rbMale.isSelected()) {
            gender = "Male";
        } else if (rbFemale.isSelected()) {
            gender = "Female";
        }

        if (name.trim().isEmpty() || gender.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name and Gender cannot be empty.", "Input error", JOptionPane.ERROR_MESSAGE);
        }

        if (trackingList.findUser(userId) != null) {
            JOptionPane.showMessageDialog(this, "User ID already exits!", "Error", JOptionPane.ERROR_MESSAGE);
        }

        User newUser = new User(userId, name, age, gender, weight, height);
        trackingList.addUser(newUser);

        JOptionPane.showMessageDialog(this, "User added succesfully!");

        clearUserFields();
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
        clearUserFields();
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnViewAllUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllUsersActionPerformed
        // TODO add your handling code here:
        displayAllUsers();
    }//GEN-LAST:event_btnViewAllUsersActionPerformed

    private void btnCalculateUserBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateUserBMIActionPerformed
        // TODO add your handling code here:
        int userId = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter User ID to calculate BMI:"));
        User user = trackingList.findUser(userId);
        if (user != null) {
            JOptionPane.showMessageDialog(this, "BMI for " + user.getName() + ": " + String.format("%.2f", user.calculateBMI()) + "\n" + user.resultBMI());
        } else {
            JOptionPane.showMessageDialog(this, "User not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalculateUserBMIActionPerformed

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    private void txtDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurationActionPerformed

    private void btnCalcCaloriesBurnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcCaloriesBurnedActionPerformed
        // TODO add your handling code here:
        int userId = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter User ID to calculate total calories burned:"));

        User user = trackingList.findUser(userId);
        if (user != null) {
            double totalCalories = 0.0;

            for (HealthRecord record : trackingList.getAllHealthRecord()) {
                if (record instanceof DailyActivity && record.getUserID() == userId) {
                    DailyActivity activity = (DailyActivity) record;
                    totalCalories += activity.calculateCaloriesBurned();
                }
            }

            JOptionPane.showMessageDialog(this, "Total Calories Burned for User " + userId + ":\n" + String.format("%.2f", totalCalories) + " kcal");

        } else {
            JOptionPane.showMessageDialog(this, "User not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcCaloriesBurnedActionPerformed

    private void txtUserID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserID2ActionPerformed

    private void txtDate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate2ActionPerformed

    private void btnViewAllNutritionRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllNutritionRecordsActionPerformed
        // TODO add your handling code here:
        displayAllRecords();
    }//GEN-LAST:event_btnViewAllNutritionRecordsActionPerformed

    private void txtRecordID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecordID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecordID3ActionPerformed

    private void txtUserID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserID3ActionPerformed

    private void txtDate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDate3ActionPerformed

    private void txtHoursSleptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoursSleptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoursSleptActionPerformed

    private void btnReset4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset4ActionPerformed
        // TODO add your handling code here:
        clearSleepFields();
    }//GEN-LAST:event_btnReset4ActionPerformed

    private void btnAddSleepRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSleepRecordActionPerformed
        // TODO add your handling code here:
        int recordId = Integer.parseInt(txtRecordID3.getText());
        int userId = Integer.parseInt(txtUserID3.getText());
        String date = txtDate3.getText();
        int hoursSlept = Integer.parseInt(txtHoursSlept.getText());

        if (date.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Date are required.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        User user = trackingList.findUser(userId);
        if (user == null) {
            JOptionPane.showMessageDialog(this, "User ID does not exist!Please add user first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (trackingList.isRecordIdExist(recordId)) {
            JOptionPane.showMessageDialog(this, "Record ID already exist!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SleepRecord newSleepRecord = new SleepRecord(user, userId, recordId, date, hoursSlept);
        trackingList.addHealthRecord(newSleepRecord);
        JOptionPane.showMessageDialog(this, "Sleep Record added successfully!");
        clearSleepFields();
    }//GEN-LAST:event_btnAddSleepRecordActionPerformed

    private void btnViewAllSleepRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllSleepRecordsActionPerformed
        // TODO add your handling code here:
        displayAllRecords();
    }//GEN-LAST:event_btnViewAllSleepRecordsActionPerformed

    private void btnEvaluateSleepForRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluateSleepForRecordActionPerformed
        // TODO add your handling code here:

        int recordId = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter Record ID to evaluate sleep duration:"));
        HealthRecord record = trackingList.findRecord(recordId);
        if (record instanceof SleepRecord sleepRecord) {
            JOptionPane.showMessageDialog(this, "Sleep Evaluation for Record" + recordId + ":" + sleepRecord.sleepCategory());
        } else {
            JOptionPane.showMessageDialog(this, "Sleep Record not found with that ID or is not a Sleep Record!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEvaluateSleepForRecordActionPerformed

    private void txtUserID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserID4ActionPerformed

    private void btnDisplayAllHealthRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAllHealthRecordsActionPerformed
        // TODO add your handling code here:
        int userId = Integer.parseInt(txtUserID4.getText());
        User user = trackingList.findUser(userId);

        if (user == null) {
            JOptionPane.showMessageDialog(this, "User not found!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StringBuilder report = new StringBuilder();

        report.append("=== HEALTH REPORT FOR: ").append(user.getName()).append(" ===\n");
        report.append("User ID : ").append(user.getUserId()).append("\n");
        report.append("Age     : ").append(user.getAge()).append("     | Gender : ").append(user.getGender()).append("\n");
        report.append("BMI     : ").append(String.format("%.2f", user.calculateBMI())).append(" (").append(user.resultBMI()).append(")\n\n");

        report.append("=== ACTIVITY RECORDS ===\n");
        for (HealthRecord r : trackingList.getAllHealthRecord()) {
            if (r instanceof DailyActivity && r.getUserID() == userId) {
                report.append("Record ID: ").append(r.getRecordID()).append("\n");
                report.append("Date: ").append(r.getDate()).append("\n");
                report.append(r.displayRecord()).append("\n\n");
            }
        }

        report.append("\n=== NUTRITION RECORDS ===\n");
        for (HealthRecord r : trackingList.getAllHealthRecord()) {
            if (r instanceof NutritionRecord && r.getUserID() == userId) {
                report.append("Record ID: ").append(r.getRecordID()).append("\n");
                report.append("Date: ").append(r.getDate()).append("\n");
                report.append(r.displayRecord()).append("\n\n");
            }
        }

        report.append("\n=== SLEEP RECORDS ===\n");
        for (HealthRecord r : trackingList.getAllHealthRecord()) {
            if (r instanceof SleepRecord && r.getUserID() == userId) {
                report.append("Record ID: ").append(r.getRecordID()).append("\n");
                report.append("Date: ").append(r.getDate()).append("\n");
                report.append(r.displayRecord()).append("\n");
            }
        }
        
        txtaReports.setText(report.toString());
    }//GEN-LAST:event_btnDisplayAllHealthRecordsActionPerformed

    private void cbMealTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMealTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMealTypeActionPerformed

    private void btnCalculateTotalDailyCaloriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateTotalDailyCaloriesActionPerformed
        // TODO add your handling code here:
        int userId = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter User ID: "));
        String date = JOptionPane.showInputDialog(this, "Enter date (YYYY-MM-DD):");

        User user = trackingList.findUser(userId);
        if (user == null) {
            JOptionPane.showMessageDialog(this, "User not found!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double totalCalories = trackingList.calculateTotalDailyCalories(userId, date);
        JOptionPane.showMessageDialog(this, "Total Calories Consumed on " + date + ":\n" + totalCalories + " kcal");
    }//GEN-LAST:event_btnCalculateTotalDailyCaloriesActionPerformed

    private void btnGenerateRecordIdDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateRecordIdDAActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        int recordID = rand.nextInt(1000, 9999);
        JOptionPane.showMessageDialog(this, "Your Record ID for Daily Activities is : " + recordID);
    }//GEN-LAST:event_btnGenerateRecordIdDAActionPerformed

    private void btnGenerateRecordIdSleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateRecordIdSleepActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        int recordID = rand.nextInt(1000, 9999);
        JOptionPane.showMessageDialog(this, "Your Record ID for Sleep Record is : " + recordID);
    }//GEN-LAST:event_btnGenerateRecordIdSleepActionPerformed

    private void btnGenerateRecordIdNutritionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateRecordIdNutritionActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        int recordID = rand.nextInt(1000, 9999);
        JOptionPane.showMessageDialog(this, "Your Record ID for Nutrition Record is : " + recordID);
    }//GEN-LAST:event_btnGenerateRecordIdNutritionActionPerformed

    private void displayAllUsers() {
        List<User> usersToDisplay = trackingList.getAllUsers();
        if (usersToDisplay.isEmpty()) {
            jTextArea1.setText("No users registered yet.");
            return;
        }
        StringBuilder sb = new StringBuilder("Registered Users:\n");
        for (User user : usersToDisplay) {
            sb.append(user.toString()).append("\n------------------------\n");

        }
        jTextArea1.setText(sb.toString());
    }

    private void displayAllRecords() {
        List<HealthRecord> allRecords = trackingList.getAllHealthRecord();
        if (allRecords.isEmpty()) {
            txtaDailyActivities.setText("No daily activity records entered yet.");
            txtaNutritionRecord.setText("No nutrition records entered yet.");
            txtaSleepRecord.setText("No sleep records entered yet.");
            return;
        }
        StringBuilder activitySb = new StringBuilder("Daily Activities:\n--------------------\n");
        StringBuilder nutritionSb = new StringBuilder("Nutrition Records:\n--------------------\n");
        StringBuilder sleepSb = new StringBuilder("Sleep Record:\n--------------------\n");

        for (HealthRecord record : allRecords) {
            if (record instanceof DailyActivity) {
                activitySb.append(record.displayRecord()).append("\n--------------------\n");
            } else if (record instanceof NutritionRecord) {
                nutritionSb.append(record.displayRecord()).append("\n--------------------\n");
            } else if (record instanceof SleepRecord) {
                sleepSb.append(record.displayRecord()).append("\n-------------------\n");
            }

        }
        txtaDailyActivities.setText(activitySb.toString());
        txtaNutritionRecord.setText(nutritionSb.toString());
        txtaSleepRecord.setText(sleepSb.toString());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthTrackingSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthTrackingSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthTrackingSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthTrackingSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthTrackingSystemGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddActivity;
    private javax.swing.JButton btnAddNutritionRecord;
    private javax.swing.JButton btnAddSleepRecord;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCalcCaloriesBurned;
    private javax.swing.JButton btnCalculateTotalDailyCalories;
    private javax.swing.JButton btnCalculateUserBMI;
    private javax.swing.JButton btnDisplayAllHealthRecords;
    private javax.swing.JButton btnEvaluateSleepForRecord;
    private javax.swing.JButton btnGenerateRecordIdDA;
    private javax.swing.JButton btnGenerateRecordIdNutrition;
    private javax.swing.JButton btnGenerateRecordIdSleep;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnReset3;
    private javax.swing.JButton btnReset4;
    private javax.swing.JButton btnViewAllActivities;
    private javax.swing.JButton btnViewAllNutritionRecords;
    private javax.swing.JButton btnViewAllSleepRecords;
    private javax.swing.JButton btnViewAllUsers;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbActivityType;
    private javax.swing.JComboBox<String> cbMealType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblActivityType;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblDate3;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHealthTrackingSystem;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHoursSlept;
    private javax.swing.JLabel lblManageNutritionRecords;
    private javax.swing.JLabel lblManageSleepRecords;
    private javax.swing.JLabel lblMealType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRecordID;
    private javax.swing.JLabel lblRecordID2;
    private javax.swing.JLabel lblRecordID3;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserID2;
    private javax.swing.JLabel lblUserID3;
    private javax.swing.JLabel lblUserID4;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDate2;
    private javax.swing.JTextField txtDate3;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHoursSlept;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRecordID;
    private javax.swing.JTextField txtRecordID2;
    private javax.swing.JTextField txtRecordID3;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserID2;
    private javax.swing.JTextField txtUserID3;
    private javax.swing.JTextField txtUserID4;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextArea txtaDailyActivities;
    private javax.swing.JTextArea txtaNutritionRecord;
    private javax.swing.JTextArea txtaReports;
    private javax.swing.JTextArea txtaSleepRecord;
    // End of variables declaration//GEN-END:variables
}
